/**
 * A minimal extractor for the SEC's ownership-form XML.
 *
 * Not a general XML parser. Node has no `DOMParser`, and pulling in a package
 * for four leaf fields on two well-known, machine-generated document shapes is
 * a worse trade than a handful of targeted regexes — the SEC's own XSD keeps
 * these tags unnested and non-repeating in the ways that matter here.
 *
 * What this deliberately does not attempt: namespaces, CDATA, entity decoding
 * beyond the handful SEC filings actually use, or anything resembling
 * arbitrary XML. If a filing needs more of the spec than this covers, it is
 * out of scope rather than silently mishandled — every accessor below returns
 * null on anything it cannot confidently read, and callers must treat that as
 * "unknown", never as "zero" or "false".
 */

/** Un-escapes the small set of entities SEC filings actually contain. */
function unescapeXml(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

/**
 * An optional XML namespace prefix before a tag name — `own:`, `com:`, and so
 * on — matched but not captured.
 *
 * Not every EDGAR filing agent writes the same document the same way. Apple's
 * Form 4s and 144s use bare tag names; Shopify's are generated by Workiva and
 * prefix every single element (`<own:nameOfPersonForWhoseAccountTheSecurities
 * AreToBeSold>`), inside the same schema, for the same form. Ignoring that
 * did not throw or error — it silently found nothing, on every field, for
 * every filing from a Workiva-generated filer. A pending-sale notice that
 * says "An insider filed notice to sell ." with every fact missing looks like
 * a rendering bug, not like a company simply using a different filing agent.
 */
const NS_PREFIX = "(?:[A-Za-z][\\w-]*:)?";

/** The first `<tag>...</tag>` anywhere in `xml`, trimmed, or null if absent or empty. */
export function tagText(xml: string, tag: string): string | null {
  const match = xml.match(new RegExp(`<${NS_PREFIX}${tag}>([\\s\\S]*?)</${NS_PREFIX}${tag}>`));
  if (!match) return null;
  const text = unescapeXml(match[1]).trim();
  return text.length > 0 ? text : null;
}

/**
 * The common `<field><value>X</value></field>` wrapper used throughout
 * Section 16 filings — nearly every fact in a Form 3/4/5 is boxed this way.
 */
export function fieldValue(xml: string, field: string): string | null {
  const wrapper = xml.match(new RegExp(`<${NS_PREFIX}${field}>([\\s\\S]*?)</${NS_PREFIX}${field}>`));
  if (!wrapper) return null;
  return tagText(wrapper[1], "value");
}

/** `fieldValue` parsed as a number, or null if absent or not finite. */
export function fieldNumber(xml: string, field: string): number | null {
  const raw = fieldValue(xml, field);
  if (raw === null) return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

/**
 * A boolean field, tolerant of the two ways these filings write one.
 *
 * The schema has changed encodings over the years without a version bump
 * consumers can key off: `<isOfficer>true</isOfficer>` and
 * `<isDirector>1</isDirector>` both appear in filings pulled minutes apart.
 * Absent is false, not unknown — a relationship flag that is missing was not
 * asserted.
 */
export function fieldBool(xml: string, field: string): boolean {
  const raw = tagText(xml, field) ?? fieldValue(xml, field);
  return raw === "true" || raw === "1";
}

/** Every top-level `<tag>...</tag>` block, for splitting a table into rows. */
export function tagBlocks(xml: string, tag: string): string[] {
  const re = new RegExp(`<${NS_PREFIX}${tag}>([\\s\\S]*?)</${NS_PREFIX}${tag}>`, "g");
  const blocks: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) blocks.push(m[1]);
  return blocks;
}
